import Numbers.Solutions.integers_no_sorry
import Numbers.Solutions.Naturals_nosorry
import Numbers.Solutions.Naturals_instances
import Numbers.Solutions.rationals_no_sorry
import Numbers.Solutions.rationals_order_no_sorry
import Numbers.Solutions.reals_no_sorry
