name: Build project, blueprint & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - name: Cleanup to free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build the project
        uses: leanprover/lean-action@v1
        with:
          use-mathlib-cache: true
          use-github-cache: false

      - name: Compile blueprint, API docs and homepage
        uses: dwrensha/docgen-action@a3f8189646977363717917b605e6de25f9704656
        with:
          api-docs: true
          blueprint: true
          homepage: home_page
